[package]
name = "aa2nucaln"
version = "0.1.1"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2021"

[dependencies]
bio = "0.41.0"
clap = {version = "3.1.18", features = ["cargo"]}
anyhow = "1.0.57"
atty = "0.2"